project_id = "cswriacqdeuvvnarhhvg"

[functions.bootstrap-admin]
verify_jwt = false

[functions.admin-upload-listing]
verify_jwt = false

[functions.admin-update-listing]
verify_jwt = false

[functions.admin-delete-listing]
verify_jwt = false

[functions.admin-rank-listing]
verify_jwt = false
